#' Impute missing values in input PredicTER dataset using defaults
#'
#' This function takes an input dataset and imputes missing values for specific columns using
#' empirically-derived default values. Default values are provided based on the empirical
#' study of environmental systematic reviews by Haddaway and Westgate (2018)
#' https://doi.org/10.1111/cobi.13231. The function relies on the 'replace_na' function in
#' the 'tidyr' package.

usedefaults <- function(planning,protocol,administration,fte,databases,db.day,greylit,greylit.day,reflists,add.search,orig.articles,percent.unique,deduping,titles.day,titles.retained,titles.checked,abstracts.day,abstracts.retained,abstracts.checked,ta.day,ta.retained,ta.checked,retrieval.day,retrieval.retained,retrieval.checked,ft.day,ft.retained,ft.checked,mdextraction.day,mdextraction.retained,mdextraction.checked,ca.day,ca.retained,ca.checked,dextraction.day,dextraction.retained,dextraction.checked,dprep.day,dprep.retained,dprep.checked,synthesis,reportwriting,comms,meetings){
  planning<-tidyr::replace_na(predicterdata$planning,20)
  protocol<-tidyr::replace_na(predicterdata$protocol,5)
  administration<-tidyr::replace_na(predicterdata$administration,19)
  fte<-tidyr::replace_na(predicterdata$fte,1)
  databases<-tidyr::replace_na(predicterdata$databases,9)
  db.day<-tidyr::replace_na(predicterdata$db.day,4)
  greylit<-tidyr::replace_na(predicterdata$greylit,16)
  greylit.day<-tidyr::replace_na(predicterdata$greylit.day,12)
  reflists<-tidyr::replace_na(predicterdata$reflists,10)
  add.search<-tidyr::replace_na(predicterdata$add.search,2)
  orig.articles<-tidyr::replace_na(predicterdata$orig.articles,11786)
  percent.unique<-tidyr::replace_na(predicterdata$percent.unique,72.1)
  deduping<-tidyr::replace_na(predicterdata$deduping,1.4)
  titles.day<-tidyr::replace_na(predicterdata$titles.day,854)
  titles.retained<-tidyr::replace_na(predicterdata$titles.retained,14.6)
  titles.checked<-tidyr::replace_na(predicterdata$titles.checked,10)
  abstracts.day<-tidyr::replace_na(predicterdata$abstracts.day,192)
  abstracts.retained<-tidyr::replace_na(predicterdata$abstracts.retained,25)
  abstracts.checked<-tidyr::replace_na(predicterdata$abstracts.checked,10)
  ta.day<-tidyr::replace_na(predicterdata$ta.day,468.14)
  ta.retained<-tidyr::replace_na(predicterdata$ta.day,1.923873641)
  ta.checked<-tidyr::replace_na(predicterdata$ta.checked,10)
  retrieval.day<-tidyr::replace_na(predicterdata$retrieval.day,171)
  retrieval.retained<-tidyr::replace_na(predicterdata$retrieval.retained,150.9)
  retrieval.checked<-tidyr::replace_na(predicterdata$retrieval.checked,0)
  ft.day<-tidyr::replace_na(predicterdata$ft.day,44)
  ft.retained<-tidyr::replace_na(predicterdata$ft.retained,21.4)
  ft.checked<-tidyr::replace_na(predicterdata$ft.checked,10)
  mdextraction.day<-tidyr::replace_na(predicterdata$mdextraction.day,16.7)
  mdextraction.retained<-tidyr::replace_na(predicterdata$mdextraction.retained,100)
  mdextraction.checked<-tidyr::replace_na(predicterdata$mdextraction.checked,0)
  ca.day<-tidyr::replace_na(predicterdata$ca.day,11.7)
  ca.retained<-tidyr::replace_na(predicterdata$ca.retained,76)
  ca.checked<-tidyr::replace_na(predicterdata$ca.checked,0)
  dextraction.day<-tidyr::replace_na(predicterdata$dextraction.day,6.9)
  dextraction.retained<-tidyr::replace_na(predicterdata$dextraction.retained,100)
  dextraction.checked<-tidyr::replace_na(predicterdata$dextraction.checked,0)
  dprep.day<-tidyr::replace_na(predicterdata$dprep.day,24)
  dprep.retained<-tidyr::replace_na(predicterdata$dprep.retained,59.2)
  dprep.checked<-tidyr::replace_na(predicterdata$dprep.checked,0)
  synthesis<-tidyr::replace_na(predicterdata$synthesis,15)
  reportwriting<-tidyr::replace_na(predicterdata$reportwriting,15)
  comms<-tidyr::replace_na(predicterdata$comms,10)
  meetings<-tidyr::replace_na(predicterdata$meetings,4)
  predicterdata<-data.frame(planning,protocol,administration,fte,databases,db.day,greylit,greylit.day,reflists,add.search,orig.articles,percent.unique,deduping,titles.day,titles.retained,titles.checked,abstracts.day,abstracts.retained,abstracts.checked,ta.day,ta.retained,ta.checked,retrieval.day,retrieval.retained,retrieval.checked,ft.day,ft.retained,ft.checked,mdextraction.day,mdextraction.retained,mdextraction.checked,ca.day,ca.retained,ca.checked,dextraction.day,dextraction.retained,dextraction.checked,dprep.day,dprep.retained,dprep.checked,synthesis,reportwriting,comms,meetings)
  return(predicterdata)
}
